---
# https://swagger.io/specification/
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md
openapi: 3.0.3
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#info-object
info:
    title: Sample Todo API
    description: Example of API design first approach and using golang stack (viper+echo+gorm+confluent+cleanarchitecture)
    termsOfService: https://console.redhat.com/api/hmsidm/v1
    version: 0.0.1
servers:
    - description: Use for Development
      url: /internal
paths:
    /livez:
        get:
            description: Probe the infrastructure is healthy and return 200 when all are healthy
            summary: Liveness kubernetes probe endpoint
            operationId: getLivez
            responses:
                '200':
                    $ref: '#/components/responses/HealthySuccess'
                default:
                    $ref: '#/components/responses/HealthyFailure'
            tags:
                - healthcheck
    /readyz:
        get:
            description: Probe the infrastructure is ready and return 200 when all are ready
            summary: Readiness kubernetes probe endpoint
            operationId: getReadyz
            responses:
                '200':
                    $ref: '#/components/responses/HealthySuccess'
                default:
                    $ref: '#/components/responses/HealthyFailure'
            tags:
                - healthcheck
components:
    responses:
        HealthyFailure:
            description: Response for unhealthy probe
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        HealthySuccess:
            description: Response for healthy probe
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/SuccessProbe'
    schemas:
        Error:
            description: Schema to define the error response
            required:
                - code
                - message
            additionalProperties: false
            properties:
                code:
                    type: integer
                    format: int32
                    example: 404
                message:
                    type: string
                    example: Not Found
        SuccessProbe:
            description: Todo schema
            type: string
            enum:
                - Ok
tags:
    - name: healthcheck
      description: Healthcheck operations
